---
#3b  Modify the previously created Play such that the "Gathering Facts" task is 
#no longer enabled. The "PLAY RECAP" should now indicate that only a single task was executed.

- name: Exercise 3a
  hosts: localhost
  gather_facts: False
  tasks:
    - ansible.builtin.debug:
        var: ansible_host
